In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel('students.xlsx')

In [5]:
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hóa,Sinh,Văn,Sử,Địa,Tiếng Anh
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,5.6,8.5
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,3.4,9.0
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,5.6,6.0
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,8.0,4.9
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,9.5,7.6
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,7.0,6.5
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,8.4,7.8
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,4.8,5.5

`.info()` shows information on each of the columns, such as the data type and number of missing values.

In [6]:
# Hiển thị thông tin về column, column types, & (missing) values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Mã học sinh  10 non-null     int64
 1   Họ tên       10 non-null     object
 2   Ngày sinh    10 non-null     datetime64[ns]
 3   Quê quán     10 non-null     object
 4   Toán         10 non-null     float64
 5   Lý           10 non-null     float64
 6   Hóa          10 non-null     float64
 7   Sinh         10 non-null     float64
 8   Văn          10 non-null     float64
 9   Sử           10 non-null     float64
 10  Địa          10 non-null     float64
 11  Tiếng Anh    10 non-null     float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(2)
memory usage: 1.1+ KB

`.shape` returns the number of rows and columns of the DataFrame.

In [8]:
df.shape

(10, 12)

`.head()` returns the first few rows (the “head” of the DataFrame)

In [9]:
# hiển thị 5 dữ liệu đầu
df.head()

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hóa,Sinh,Văn,Sử,Địa,Tiếng Anh
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,5.6,8.5
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,3.4,9.0
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,5.6,6.0
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8

`.tail()` returns the last few rows

In [10]:
# hiển thị 5 dữ liệu cuối
df.tail()

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hóa,Sinh,Văn,Sử,Địa,Tiếng Anh
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,8.0,4.9
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,9.5,7.6
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,7.0,6.5
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,8.4,7.8
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,4.8,5.5

In [9]:
# trả về dataframe nhưng bỏ đi các thông tin Object(Họ tên, Quê Quán)
df.describe()

,Mã học sinh,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh
count,1.000000e+01,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,2.020521e+07,6.910000,7.080000,6.920000,6.180000,6.310000,5.750000,6.440000,6.510000
std,3.027650e+00,1.481328,1.015218,1.180207,1.966836,1.323673,2.147996,1.992319,1.674946
min,2.020521e+07,4.200000,5.600000,5.400000,2.000000,4.000000,2.000000,3.400000,3.800000
25%,2.020521e+07,5.875000,6.575000,6.100000,5.250000,5.500000,4.525000,5.000000,5.500000
50%,2.020521e+07,7.000000,7.000000,6.750000,6.650000,6.500000,5.700000,6.300000,6.250000
75%,2.020522e+07,7.875000,7.625000,7.450000,7.000000,6.925000,7.250000,7.950000,7.750000
max,2.020522e+07,9.300000,9.000000,8.800000,9.000000,8.500000,9.200000,9.500000,9.000000

In [14]:
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,5.6,8.5
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,3.4,9.0
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,5.6,6.0
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,8.0,4.9
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,9.5,7.6
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,7.0,6.5
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,8.4,7.8
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,4.8,5.5

In [21]:
df.count()

Mã học sinh    10
Họ tên         10
Ngày sinh      10
Quê quán       10
Toán           10
Lý             10
Hoá            10
Sinh           10
Văn            10
Sử             10
Địa            10
Tiếng Anh      10
dtype: int64

### Có bao nhiêu học sinh ở từng tỉnh thành tham gia kì thi tốt nghiệp

In [15]:
df['Quê quán']

0        Hà Nội
1    Quảng Bình
2        Hà Nam
3      Bắc Ninh
4     Thái Bình
5        Hà Nội
6      Nam Định
7      Bắc Ninh
8        Hà Nội
9        Hà Nội
Name: Quê quán, dtype: object

In [48]:
# Có bao nhiêu học sinh ở từng tỉnh thành tham gia kì thi tốt nghiệp
std = df.groupby(['Quê quán']).size().reset_index(name='Mã học sinh')
std

     Quê quán  Mã học sinh
0    Bắc Ninh            2
1      Hà Nam            1
2      Hà Nội            4
3    Nam Định            1
4  Quảng Bình            1
5   Thái Bình            1

In [47]:
# Using value_counts
df['Quê quán'].value_counts()

Hà Nội        4
Bắc Ninh      2
Quảng Bình    1
Hà Nam        1
Thái Bình     1
Nam Định      1
Name: Quê quán, dtype: int64

### Thí sinh nào nhiều tuổi nhất, ít tuổi nhất

In [49]:
# Thí sinh nào nhiều tuổi nhất, ít tuổi nhất
result_age = df.groupby('Họ tên').agg({'Ngày sinh': ['min', 'max']})
result_age

                  Ngày sinh
                        min        max
Họ tên
Hoàng Trung Sơn  2000-08-27 2000-08-27
Hà Trung Kiên    2000-04-03 2000-04-03
Lê Minh Hoàng    2001-02-11 2001-02-11
Nguyễn Thanh Oai 2000-05-25 2000-05-25
Nguyễn Thị Linh  2000-12-17 2000-12-17
Nguyễn Văn Thành 2000-05-20 2000-05-20
Nguyễn Đức Bình  2000-03-10 2000-03-10
Trần Trang Nhung 2002-07-05 2002-07-05
Võ Hoàng Yến     2000-06-21 2000-06-21
Đặng Ngọc Sơn    2000-01-25 2000-01-25

In [55]:
youngest = df["Ngày sinh"].max() # nhỏ nhất

In [53]:
oldest = df["Ngày sinh"].min() # lớn nhất

In [26]:
df[df["Ngày sinh"] == youngest]

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5

In [23]:
df[df["Ngày sinh"] == oldest]

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8

In [50]:
# Thí sinh nào nhiều tuổi nhất
oldest_student = df[df['Ngày sinh'] == oldest]
oldest_student[['Họ tên', 'Ngày sinh']]

          Họ tên  Ngày sinh
4  Đặng Ngọc Sơn 2000-01-25

In [56]:
# Thí sinh nào nhiều tuổi nhất
youngest_student = df[df['Ngày sinh'] == youngest]
youngest_student[['Họ tên', 'Ngày sinh']]

             Họ tên  Ngày sinh
2  Trần Trang Nhung 2002-07-05

### Tính số lượng sinh viên có điểm thi từng môn trong từng phổ điểm

In [ ]:
# Chia phổ điểm từ 0-10 thành 10 đoạn (0-1, 1-2, 2-3,..9-10). Tính số lượng sinh viên có điểm thi từng môn trong từng phổ điểm trên

In [ ]:
# Tính điểm trung bình các môn của từng học sinh và cho cột điểm này vào bộ dữ liệu. 
# Biết rằng các môn Toán, Văn, và tiếng Anh hệ số 2.0, các môn còn lại hệ số 1.0

In [58]:
subjects = ['Toán', 'Lý', 'Hoá', 'Sinh', 'Văn', 'Địa', 'Tiếng Anh']
dtb = df[subjects]
dtb

   Toán   Lý  Hoá  Sinh  Văn  Địa  Tiếng Anh
0   7.0  8.0  8.8   6.8  4.0  5.6        8.5
1   5.6  7.7  6.0   7.0  6.5  3.4        9.0
2   4.2  6.5  5.4   8.0  7.0  4.3        5.5
3   8.0  5.6  6.5   7.0  7.5  5.6        6.0
4   9.3  5.8  7.5   4.5  6.5  7.8        3.8
5   5.6  7.0  5.6   5.0  6.4  8.0        4.9
6   6.7  6.8  7.3   6.0  6.7  9.5        7.6
7   7.5  9.0  7.0   2.0  5.2  7.0        6.5
8   7.0  7.4  6.4   9.0  8.5  8.4        7.8
9   8.2  7.0  8.7   6.5  4.8  4.8        5.5

In [60]:
tva = ['Toán', 'Văn', 'Tiếng Anh']
lhs = ['Lý', 'Hoá', 'Sinh', 'Địa']
dtb = (df[tva].sum(axis=1) * 2 + df[lhs].sum(axis=1)) / 10
dtb

0    6.82
1    6.63
2    5.76
3    6.77
4    6.48
5    5.94
6    7.16
7    6.34
8    7.78
9    6.40
dtype: float64

In [33]:
df['Trung bình'] = dtb

In [34]:
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh,Trung bình
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,5.6,8.5,6.82
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,3.4,9.0,6.63
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5,5.76
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,5.6,6.0,6.77
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8,6.48
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,8.0,4.9,5.94
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,9.5,7.6,7.16
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,7.0,6.5,6.34
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,8.4,7.8,7.78
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,4.8,5.5,6.40

### Tính điểm cho các khối A, A1, B, C, D

In [61]:
A = df[['Toán', 'Lý', 'Hoá']].sum(axis=1)
df['Khối A'] = A

In [63]:
A1 = df[['Toán', 'Lý', 'Tiếng Anh']].sum(axis=1)
df['Khối A1'] = A1

In [65]:
B = df[['Toán', 'Hoá', 'Sinh']].sum(axis=1)
df['Khối B'] = B

In [68]:
C = df[['Văn', 'Sử', 'Địa']].sum(axis=1)
df['Khối C'] = C

KeyError: "['Sử'] not in index"

In [72]:
tv = ['Toán', 'Văn']
#D = df[['Toán', 'Văn', 'Anh']].sum(axis=1)
D = (df['Tiếng Anh'] * 2 + df[tv].sum(axis=1)) / 10
df['Khối D'] = D

In [74]:
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh,Trung bình,Khối A,passA,Khối A1,Khối B,Khối D
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,5.6,8.5,6.82,23.8,pass,23.5,22.6,2.80
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,3.4,9.0,6.63,19.3,fail,22.3,18.6,3.01
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5,5.76,16.1,fail,16.2,17.6,2.22
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,5.6,6.0,6.77,20.1,fail,19.6,21.5,2.75
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8,6.48,22.6,fail,18.9,21.3,2.34
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,8.0,4.9,5.94,18.2,fail,17.5,16.2,2.18
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,9.5,7.6,7.16,20.8,fail,21.1,20.0,2.86
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,7.0,6.5,6.34,23.5,pass,23.0,16.5,2.57
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,8.4,7.8,7.78,20.8,fail,22.2,22.4,3.11
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,4.8,5.5,6.40,23.9,pass,20.7,23.4,2.40

### Xét tuyển đầu vào các khối

In [75]:
# fail or pass A: 23.5
passA = []
for i in df['Khối A']:
    if i >= 23.5:
        passA += ['pass']
    else:
        passA += ['fail']

df['passA'] = passA

In [76]:
# fail or pass A1: 22
passA1 = []
for i in df['Khối A1']:
    if i >= 22:
        passA1 += ['pass']
    else:
        passA1 += ['fail']

df['passA1'] = passA1

In [77]:
# fail or pass B: 21.5
passB = []
for i in df['Khối B']:
    if i >= 21.5:
        passB += ['pass']
    else:
        passB += ['fail']

df['passB'] = passB

In [ ]:
# fail or pass C: 22.5
passC = []
for i in df['Khối C']:
    if i >= 22.5:
        passC += ['pass']
    else:
        passC += ['fail']

df['passC'] = passC

In [78]:
# fail or pass D: 27.5
passD = []
for i in df['Khối D']:
    if i >= 27.5:
        passD += ['pass']
    else:
        passD += ['fail']

df['passD'] = passD

In [79]:
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,...,Tiếng Anh,Trung bình,Khối A,passA,Khối A1,Khối B,Khối D,passA1,passB,passD
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,...,8.5,6.82,23.8,pass,23.5,22.6,2.80,pass,pass,fail
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,...,9.0,6.63,19.3,fail,22.3,18.6,3.01,pass,fail,fail
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,...,5.5,5.76,16.1,fail,16.2,17.6,2.22,fail,fail,fail
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,...,6.0,6.77,20.1,fail,19.6,21.5,2.75,fail,pass,fail
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,...,3.8,6.48,22.6,fail,18.9,21.3,2.34,fail,fail,fail
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,...,4.9,5.94,18.2,fail,17.5,16.2,2.18,fail,fail,fail
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,...,7.6,7.16,20.8,fail,21.1,20.0,2.86,fail,fail,fail
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,...,6.5,6.34,23.5,pass,23.0,16.5,2.57,pass,fail,fail
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,...,7.8,7.78,20.8,fail,22.2,22.4,3.11,pass,pass,fail
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,...,5.5,6.40,23.9,pass,20.7,23.4,2.40,fail,pass,fail

### So sánh điểm trung bình các khối vào đại học

In [43]:
tbA = df['Khối A'].mean()
tbA

20.910000000000004

In [80]:
tbA1 = df['Khối A1'].mean()
tbA1

20.499999999999996

In [81]:
tbB = df['Khối B'].mean()
tbB

20.01

In [ ]:
tbC = df['Khối C'].mean()
tbC

In [83]:
tbD = df['Khối D'].mean()
tbD

2.6239999999999997

### Xếp loại học lực học sinh

In [96]:
import numpy as np

def judge(x):
    if any(x > 8.0):
        return 'Xuất sắc'
    else:
        return 'Trung bình'

tb = np.array(df['Trung bình'])
if tb.any() > 9.0:
    df['Học lực'] = df[['Toán', 'Lý', 'Hoá']].apply(judge, axis=1)

In [97]:
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,...,Tiếng Anh,Trung bình,Khối A,passA,Khối A1,Khối B,Khối D,passA1,passB,passD
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,...,8.5,6.82,23.8,pass,23.5,22.6,2.80,pass,pass,fail
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,...,9.0,6.63,19.3,fail,22.3,18.6,3.01,pass,fail,fail
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,...,5.5,5.76,16.1,fail,16.2,17.6,2.22,fail,fail,fail
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,...,6.0,6.77,20.1,fail,19.6,21.5,2.75,fail,pass,fail
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,...,3.8,6.48,22.6,fail,18.9,21.3,2.34,fail,fail,fail
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,...,4.9,5.94,18.2,fail,17.5,16.2,2.18,fail,fail,fail
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,...,7.6,7.16,20.8,fail,21.1,20.0,2.86,fail,fail,fail
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,...,6.5,6.34,23.5,pass,23.0,16.5,2.57,pass,fail,fail
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,...,7.8,7.78,20.8,fail,22.2,22.4,3.11,pass,pass,fail
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,...,5.5,6.40,23.9,pass,20.7,23.4,2.40,fail,pass,fail